# @package _global_
task: incompression

incompression:
  model: SimianLuo/LCM_Dreamshaper_v7
  lr: 1e-4
  sample_batch_size_per_gpu: 4
  train_batch_size_per_gpu: 2
  num_sample_iters: 1
  clip_range: 0.0001
  max_grad_norm: 5
  adv_clip_max: 10
  gradient_accumulation_steps: 2
  num_epochs: 100
  num_inference_steps: 8
  batches_per_epoch: 10
  stat_buffer_size: 16
  stat_min_count: 16
  num_inner_epochs: 1
  lora_alpha: 32
  lora_r: 16
  dataset: ComplexAnimals
  reward_fn: incompressibility