wandb:
  log: true
  entity: diffusion_cornell
  project: prompt_image_alignment
  name: pia_rlcm_32max_8min_count_${now:%Y-%m-%d_%H-%M-%S}

hydra:
  run:
    dir: outputs/${wandb.name}/${now:%Y-%m-%d_%H-%M-%S}

training:
  lcm_origin_steps: 50
  guidance_scale: 8.0
  save_interval: 10
  max_prompt_length: 50
  logdir: "logs"

defaults:
  - _self_
  - task: aesthetic
